import 'dart:async';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:permission_handler/permission_handler.dart';
import 'firebase_options.dart';
import 'services/auth_service.dart';
import 'services/scam_number_service.dart';
import 'app.dart';
// Generated by flutterfire configure -- run:
// dart pub global activate flutterfire_cli
// flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID
// import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  // Replace with: options: DefaultFirebaseOptions.currentPlatform
  // after running flutterfire configure
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform
  );

  // Sign in anonymously so Firestore/Firebase AI rules can apply
  final authService = AuthService();
  await authService.signInAnonymously();

  // Request critical permissions at startup
  await _requestStartupPermissions();

  // Kick off background scam number cache sync
  unawaited(_initialCacheSync());

  runApp(const MayaShieldApp());
}

Future<void> _requestStartupPermissions() async {
  await [
    Permission.phone,
    Permission.contacts,
    Permission.microphone,
    Permission.notification,
  ].request();
}

Future<void> _initialCacheSync() async {
  try {
    final service = ScamNumberService();
    await service.syncToLocalCache();

    // Schedule periodic re-sync every 30 minutes
    Timer.periodic(const Duration(minutes: 30), (_) async {
      if (service.needsSync) await service.syncToLocalCache();
    });
  } catch (_) {}
}

void unawaited(Future<void> future) {}
